#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

sudo: required

cache:
  timeout: 10000
  directories:
  - $HOME/.m2

services:
  - docker

env:
  matrix:
    - INFLUXDB_VERSION=1.7 INFLUXDB_2_VERSION=nightly

install: true

script:
  - ./scripts/influxdb-restart.sh
  - mvn -B clean install -Dmaven.javadoc.skip=true
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
  - stage: site
    if: branch = master & repo = bonitoo-io/influxdb-client-java
    jdk: oraclejdk8
    script:
      - ./scripts/influxdb-restart.sh
      - ./scripts/publish-site.sh

  - stage: deploy
    jdk: oraclejdk8
    script: skip
    deploy:
      provider: script
      script: mvn clean deploy -DskipTests -s scripts/deploy-settings.xml
      skip_cleanup: true
      on:
        repo: bonitoo-io/influxdb-client-java
        branch: master

after_failure:
  - cat target/surefire-reports/*.txt
